### ISSUE TITLE
Please provide an updated release ZIP

### ISSUE THREAD

**Issue by seanthegeek** [dzzie/VS_LIBEMU#7]
I would like to include scdbg as a [proposed package](https://github.com/mandiant/VM-Packages/issues/new?assignees=&labels=%3Anew%3A+package&template=new_package.yml&title=Package+proposal%3A+scdbg.vm) for Mandiant's [FLARE-VM](https://github.com/mandiant/flare-vm) project.

That requires a URL to a ZIP file that contains all of the release files (CLI EXE, GUI EXE, and help file) in a single zip file. Additionally. the URL of the zip file must be unique to that release/versions, as the file hash of the ZIP will be checked against a known file hash.

The easiest way to do this would be to post each new release ZIP as a new release on the GitHub releases feature.

**Comment by dzzie** [comment]
https://github.com/dzzie/VS_LIBEMU/releases/tag/12.7.22

**Comment by dzzie** [comment]
if you would like a release for vbdec as well let me know I can create a release with changlog and binary. its a significant reversing tool for vb6  http://sandsprite.com/vbdec/

**Comment by seanthegeek** [comment]
Nice! sure!

**Comment by dzzie** [comment]
do your scripts automatically pickup new releases as they are posted or do you need notification and then manually update links?

ultimately with the MS takeover of github and copilot ai thing I would like to disentangle myself from github. The best scenario for me is just hosting them on sandsprite but thats http only. Unless you have a recommendation of a good free file host you could pull directly from, or had your own mirror repo you could pull from. 

honestly having your own controlled mirrors is probably the safest and control link rot.
